# Use the official Node.js 16 image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY mb-fe/package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY mb-fe .

# Build the React app
RUN npm run build

# Serve the React app with a static server
CMD ["npx", "serve", "-s", "build", "-l", "3000"]

# Expose the port the app runs on
EXPOSE 3000
