version: '3.9'

services:
  go-app:
    container_name: go-app
    image: henry/go-app:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile-be
    environment:
        # POSTGRES_PASSWORD: 1234
        # POSTGRES_USER: root
        # POSTGRES_DDATABASE: postgres
        # POSTGRES_HOST: go_db
        # POSTGRES_PORT: 5432
      DATABASE_URL: "host=go_db user=root password=1234 dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    restart: always
    volumes:
      - .:/app
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
        - pgdata:/var/lib/postgresql/data
        - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
  app:
    build:
      context: ./
      dockerfile: Dockerfile-fe
    container_name: app
    depends_on:
      - go_db
      - go-app
    env_file:
      - ./mb-fe/.env.local 
    ports:
      - "3000:3000"
      - "5001:5001"
      - "8545:8545"
    volumes:
      - ./mb-fe:/usr/src/app
 
volumes:  
  pgdata: {}      