# Use an official Golang runtime as a base image
FROM golang:1.16.3-alpine3.13
 
# Set the working directory inside the container
WORKDIR app/

# Copy the local package files to the container's workspace
COPY ./mb-be/go.mod .
COPY ./mb-be/go.sum .
 
COPY ./mb-be/ .
# Download and install the dependencies
RUN go mod download
 
# Build the Go app
RUN go build -o api ./cmd/main.go 
 
 
#EXPOSE the port
EXPOSE 8000
 
# Run the executable
CMD ["./api", "-H", "0.0.0.0"]
