# use official Golang image
FROM golang:1.16.3-alpine3.13

# set working directory
WORKDIR /app/mb-be

# Copy the source code
COPY ./mb-be . 

# Download and install the dependencies
RUN go get -d -v ./...

# Build the Go app
RUN go mod tidy

#EXPOSE the port
EXPOSE 8000

# Run the executable
CMD ["./api/api"]
