version: '3.9'

services:
  go-app:
    container_name: go-app
    image: henry/go-app:1.0.0
    build: 
      context: .
      dockerfile: Dockerfile-be
    environment:
      DATABASE_URL: "host=go_db user=admin password=1234 dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    restart: always
    volumes:
      - .:/app
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: ./
      dockerfile: Dockerfile-fe
    container_name: app
    depends_on:
      - go_db
      - go-app
    env_file:
      - ./mb-fe/.env 
    ports:
      - "3000:3000"
volumes:  
  pgdata: {}
