version: '3.7'

services:
  go-app:
    container_name: go-app
    image: henry/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=root password=1234 dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
    restart: always
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf

volumes:  
  pgdata: {}
